# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # DÃ©marrage de session automatique si on lit/Ã©crit dedans
    session: true

    # ðŸ”¹ Active le composant Form
    form: true

    # ðŸ”¹ Active la protection CSRF (utile pour les formulaires)
    csrf_protection: true

    # ðŸ”¹ Active le systÃ¨me de validation (contraintes @Assert, etc.)
    validation:
        enabled: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
